import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/layout/navigation/main-navigation";
import Header from "@/components/layout/header/header";
import Logo from "@/components/common/logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header>
          <Logo />
          <MainNavigation />
        </Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
